name: qa-retriever-eval
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0
  - attrs=19.3.0
  - backcall=0.1.0
  - bleach=3.1.5
  - brotlipy=0.7.0
  - ca-certificates=2020.4.5.2
  - certifi=2020.4.5.2
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.9.2
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - elasticsearch=7.7.1
  - entrypoints=0.3
  - expat=2.2.9
  - gettext=0.19.8.1
  - glib=2.64.3
  - icu=64.2
  - idna=2.9
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - ipykernel=5.3.0
  - ipython=7.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - jpeg=9d
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - krb5=1.17.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgfortran=4.0.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libopenblas=0.3.9
  - libpng=1.6.37
  - libpq=12.2
  - libsodium=1.0.17
  - llvm-openmp=10.0.0
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.1
  - notebook=6.0.3
  - nspr=4.20
  - nss=3.47
  - numpy=1.18.5
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=1.0.4
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.1.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2020.1
  - pyzmq=19.0.1
  - qt=5.12.5
  - qtconsole=4.7.4
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.23.0
  - send2trash=1.5.0
  - setuptools=47.1.1
  - six=1.15.0
  - sqlite=3.30.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.0.4
  - tqdm=4.46.1
  - traitlets=4.3.3
  - urllib3=1.25.9
  - wcwidth=0.2.3
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1


